### ISSUE TITLE
Reading data

### ISSUE THREAD

**Issue by tdelubac** [tdelubac/Correlation#2]
@BloodOrange dis moi si tu es ok avec la class Data. Après je peux la puller sur la branche master

**Comment by BloodOrange** [comment]
Je suis actuellement en train de mettre en place le fichier de configuration pour cmake, mais je suis parti du master. J'ai créé un main.cpp avec un hello world :). 
Après je vais voir pour mettre la première page du wiki, qui explique comment compiler.

Pour le Data, j'ai vu plusieurs trucs qui me semble bizarre. La principale c'est que tes méthodes retournes un vector<>. Si je ne dis pas de connerie, ça copie le tableau à chaque appelle d'une méthode. J'ai juste jeté un coup d'oeil rapide pour le moment.

**Comment by tdelubac** [comment]
Ouch ! quand tu retournes ça fait le copie constructor ? Il faut donc que je passe par référence ?

Pour le main, il y en a déjà un dans la branche opening_data sous le nom "correlation.cpp" dans le dossier src.

**Comment by tdelubac** [comment]
J'ai pousser le fichier data.h sans modif sur le master. Je regarde comment passer les vecteurs par référence demain.

**Comment by tdelubac** [comment]
J'ai modifié la classe data.h pour retourner des const references des fonctions membre au lieu de retourner par valeur. J'ai testé et ça ne fait plus de copie du vecteur. Je ferme l'issue.
